import assert from 'node:assert/strict'

/** Runs inside a real, hidden Electron window using an isolated database. */
export async function run(window, bridge) {
  const js = code => window.webContents.executeJavaScript(code)
  const until = expression => js(`new Promise((resolve, reject) => { let n = 0; const timer = setInterval(() => { if (${expression}) { clearInterval(timer); resolve(true) } else if (++n > 160) { clearInterval(timer); reject(new Error(document.querySelector('#status').textContent)) } }, 25) })`)
  const click = selector => js(`document.querySelector(${JSON.stringify(selector)}).click()`)
  const fill = (selector, value, type = 'input') => js(`(() => { const node = document.querySelector(${JSON.stringify(selector)}); node.${typeof value === 'boolean' ? 'checked' : 'value'} = ${JSON.stringify(value)}; node.dispatchEvent(new Event(${JSON.stringify(type)}, { bubbles: true })); })()`)
  await until("document.querySelectorAll('#views button').length === 4")
    await until("document.querySelector('#alaya-startup')===null")
  // Fresh profiles open in the notebook; this suite drives the memory board.
  await until("document.body.dataset.mode==='mistakebook'")
  await click('#mb-mode-switch'); await until("document.body.dataset.mode==='memory'")
  await click('#manage-groups')
  await until("document.querySelector('#new-group-name')")
  await fill('#new-group-name', '界面测试组')
  await click('#create-group')
  await until("document.querySelector('#tree').textContent.includes('界面测试组')")
  const group = bridge.vault.store.requireGroup('界面测试组')
  await js("document.querySelector('dialog').close()")
  await click('#new')
  await fill('[data-field="title"]', '跨宿主记忆')
  await fill('[data-field="content"]', '## 接口约定\nCodex 和 DSH 使用同一份记忆。\n\n- 确认结论后保存\n- 临时进度留在对话记忆')
  await fill('[data-field="tagsText"]', '接口, 约定')
  await fill('[data-field="priority"]', '90')
  await fill('[data-field="base"]', true)
  await click('#save-entry')
  await until("document.querySelector('#status').textContent === '记忆已创建'")
  let entry = bridge.vault.store.listEntries({ limit: 20 }).find(row => row.title === '跨宿主记忆')
  assert.ok(entry); assert.equal(entry.priority, 90); assert.equal(entry.base, true)
  assert.deepEqual(entry.tags.filter(tag => tag !== '人工输入'), ['接口', '约定'])
  await fill('[data-field="title"]', '界面操作验证')
  await fill('[data-field="scope"]', 'conversation', 'change')
  await fill('[data-field="groupId"]', group.id, 'change')
  await click('#save-entry')
  await until("document.querySelector('#status').textContent === '修改已保存'")
  entry = bridge.vault.store.requireEntry(entry.id)
  assert.equal(entry.title, '界面操作验证'); assert.equal(entry.scope, 'conversation'); assert.equal(entry.groupId, group.id)
  await js("[...document.querySelectorAll('#drawer button')].find(button => button.textContent === '隐藏').click()")
  await until("document.querySelector('#status').textContent === '可见性已更新'")
  assert.equal(bridge.vault.store.requireEntry(entry.id).hidden, true)
  await js("[...document.querySelectorAll('#views button')].find(button => button.textContent.startsWith('隐藏')).click()")
  await until("document.querySelector('#list .tile')?.textContent.includes('界面操作验证')")
  await click('#list .tile')
  await until("document.querySelector('#drawer [data-field=title]')")
  await js("[...document.querySelectorAll('#drawer button')].find(button => button.textContent === '恢复显示').click()")
  await until("document.querySelector('#status').textContent === '可见性已更新'")
  assert.equal(bridge.vault.store.requireEntry(entry.id).hidden, false)
  await js("[...document.querySelectorAll('#views button')].find(button => button.textContent.startsWith('全部记忆')).click()")
  await until("document.querySelector('#list .tile')")
  await fill('#query', '界面操作验证')
  await until("document.querySelectorAll('#list .tile').length === 1")
  await click('#settings')
  await until("document.querySelector('textarea[aria-label=\"Codex 接口配置\"]')")
  const config = await js("document.querySelector('textarea[aria-label=\"Codex 接口配置\"]').value")
  assert.ok(config.includes('"mcp"')); assert.ok(config.includes('sqlite'))
  const save = await js("window.vault.settings({ baseUrl: 'http://127.0.0.1:9999/v1', model: 'mock-only', apiKey: 'ui-dummy-key' })")
  assert.equal(save.ok, true); assert.equal(save.result.hasKey, true)
  assert.equal(save.result.encryptedKey, undefined); assert.ok(!JSON.stringify(save).includes('ui-dummy-key'))
  const clear = await js("window.vault.settings({ baseUrl: '', model: '', clearKey: true })")
  assert.equal(clear.result.hasKey, false)
  await js("document.querySelector('dialog').close()")
  await fill('#query', '')
  await until("document.querySelector('#list .tile')")
  await bridge.invoke('group.create', { name: '开发规范', scope: 'knowledge' })
  await bridge.invoke('entry.write', { group: '开发规范', title: '发布前检查', content: '运行回归测试，检查安装包和数据库备份，再发布版本。', tags: ['发布'], priority: 70 })
  await bridge.invoke('entry.write', { group: '知识库', title: '共用一个数据库', content: '桌面程序、Codex MCP、DSH 插件与命令行都指向同一个数据库文件。', tags: ['接口'], priority: 90 })
  await click('#refresh')
  await until("document.querySelectorAll('#list .tile').length >= 3")
  await js("[...document.querySelectorAll('#list .tile')].find(button => button.textContent.includes('共用一个数据库')).click()")
  await until("document.querySelector('#drawer [data-field=title]')?.value === '共用一个数据库'")
  assert.equal(await js('typeof window.require'), 'undefined')
  assert.equal(await js('typeof window.process'), 'undefined')
  console.log('Desktop UI: groups, create, edit, scope, move, labels, priority, base, hide, restore, search, connectors and encrypted key passed')
}
